### PR TITLE
adapt edit_MarkerFiles.m

### PR DESCRIPTION
**Pull request by Paul-Baudin**
Hi Stephen,
I thought that you would be interested by it. It is highly inspired by the script development/editMarkerfiles.m (thanks +++), and I adapted it a little bit for some needs I had. I did not modify the script in /development in case you still need it. 
If you think you could use it I can put it in the /shared folder.
Paul

### CODE REVIEW

**Review by stephenwhitmarsh — COMMENTED** [review]
Nice. But for /shared I am not sure; Can the same thing not be accomplished with three existing functions?: Reading the musemarkers using readMuseMakers, then using (a perhaps improved) editMuseMarkers, then writeMuseMarkers? This way the code stays modular, and any change in one of those functions would keep everything consistent, instead of having different ways of reading and writing musemarkers etc. embedded in different functions. In other words, this function has a lot of double (and potentially soon asynchronous) code.

**Comment by stephenwhitmarsh** [comment]
To be clear, editMarkerfile is not doing this well either! I will write a proper editMuseMarkers now and push it ASAP. Stay tuned :-)

**Comment by stephenwhitmarsh** [comment]
See https://github.com/stephenwhitmarsh/EpiCode/commit/20ec9c079ce8d4dcc92a21c63d6d097aa713e426

**Comment by Paul-Baudin** [comment]
Great, thanks !
________________________________
De : Stephen Whitmarsh <notifications@github.com>
Envoyé : mardi 15 septembre 2020 13:08
À : stephenwhitmarsh/EpiCode <EpiCode@noreply.github.com>
Cc : BAUDIN Paul <paul.baudin@icm-institute.org>; Author <author@noreply.github.com>
Objet : Re: [stephenwhitmarsh/EpiCode] adapt edit_MarkerFiles.m (#29)


Closed #29<https://github.com/stephenwhitmarsh/EpiCode/pull/29>.

**Pull request closed without merging**
