### PR TITLE
prepare data for Spyking Circus

### PR DESCRIPTION
**Pull request by Paul-Baudin**
Hi Stephen,
Here is a first pull request, others will follow. This is for functions I updated to better prepare data for Spyking Circus

- addMuseBAD.m : I better documented it and added the possibility to add BAD marker at the begining, or the end of the file.

- writeSpykingCircus.m : removed the old field 'events' which do not exist anymore in MuseStruct, and replace it with synctime.

- writeSpykingCircusDeadFile.m : I adapted it so I can launch it with different MuseStruct depending on the artefacts I want to put (eg seizures or not). I added a suffix variable in input option, so I can create several deadfiles with different suffixs for the same patient. I did'nt do as many modifications as the Git representation would let you think. I think it does that because I removed or add a 'if' or a 'for' and aligned all the text with it.

- writeSpykingCircusParameters.m : maybe would it be better to add it to writeSpykingCircus.m ? I corrected little bugs in filename and nb_chans, and used the 'ms' dead file and not the 'sample' file because I found it easier to understand (I can more easily check the ms timings than the sample timings on Muse to see if there was mistakes, for example). And I added the automatic creation of slurm script. 

Cheers,
Paul

### CODE REVIEW

**Comment by stephenwhitmarsh** [comment]
Hi Paul,

Thanks a lot! Thanks for fixing the outdated parts (events vs synctime
etc), and adding the bad markers. addMuseBAD has great documentation!

*writeSpykingCircusDeadFile*: while adding an optional suffix is fine as it
helps you and probably others with a similar flexible way of creating
artefacts, I do not agree on the implementation:
Adding another input option besides the cfg and the data is confusing as it
is inconsistent with other functions, it is not very transparent, it is
easy to make a mistake in the order of input arguments, and it will break
existing code. I admit that it already had the ugly 'part list', which
should have been removed as well.
It is interesting to note the two different ways in which FieldTrip and
MATLAB deal with configurations of functions. You can see this difference
in Python as well:
MATLAB uses field-value pairs, e.g. plot(x,y,'LineColor','Blue'); where
Fieldtrip places all configuration in a cfg. Both methods provide an
explicit mapping between a variable name and a value. Alas, in MATLAB you
can also use something like plot(x,y,'b'). But the reason is that otherwise
code can become so long that it becomes unreadable. Fieldtrip uses the cfg
as a way to make the code readable, and allow you to define a variable on
every line (e.g. cfg.data = x,y; cfg.color = 'blue').
Anyway, I try to follow FieldTrip's use of cfg fields and keep the input
fields of the functions as consistent as possible: configuration, data,
MuseStruct, Force; If needed we can deviate and add, but I think that your
prefix could be placed in the configuration field. Of course you can edit
that in your main script, it will just cost you one line of extra code.

By the way, MuseStruct was separated from the datastructure at one point,
but remained too complex to add as a field in the configuration (FieldTrip
deals with similar problems sometimes).
Thinking of it now, it would be better if also the 'force' field goes into
the configuration. I will make a github issue for that, and see if we can
find a moment to change all the code for that.
To come back to the prefix - please make it an *optional *field in the
configuration: if there is e.g. no 'cfg.circus.deadfileprefix' make it
empty and retain the same filename as it is now.
If you could remove the 'part list' input that would be great. Even better
if you could make it an *optional *field in the configuration.

*writeSpykingCircusParameters *used to be part of writeSpykingCircus, but
the latter takes a LOT of time, and is in the end really doing something
else, and you want to run them separately sometimes. I don't see much added
benefit putting them together again.
Also, I would prefer not to add the slurm script to
writeSpykingCircusParameter. This is too specific, and too hard-coded (the
options for slurm are not set in a configuration by the user) for your use
case. Please create a separate matlab script for slurm, and perhaps for now
place it in your project directory rather than the shared one. People can
copy and adapt it to their own use then. Okay? Other people might want to
do it differently.

I hope you agree with the above! Please either change accordingly in this
branch and commit, or make a new branch/PR.

Cheers,
Stephen















Op wo 17 jun. 2020 om 12:12 schreef Paul-Baudin <notifications@github.com>:

**Comment by Paul-Baudin** [comment]
Hi Stephen,
I didn't think about it but indeed it completely makes sens. I will convert the input into a cfg structure and set the optionnal fields.
And I will remove the slurm script of the function also.
Thanks for your advices !
Paul

**Comment by Paul-Baudin** [comment]
Hi Stephen,
I added your comments. Also, I added some 'continue' statements and 'ft_getopt' because I found it very good for the clarity of the code and the management of the cfg input. 
Also, I added documentations
Let me know if you think of anything else to improve it :)
Cheers 
Paul

**Comment by Paul-Baudin** [comment]
A little modification in addMuseBAD, I forgot to adapt this line

**Comment by Paul-Baudin** [comment]
Done, and tested :)

**Comment by stephenwhitmarsh** [comment]
thanks! merged!

Op do 18 jun. 2020 om 15:44 schreef Paul-Baudin <notifications@github.com>:

**Pull request merged**
