### PR TITLE
Template sc

### PR DESCRIPTION
**Pull request by Paul-Baudin**
Hi Stephen,
Share you some modifs in the template for Spyking Circus params which I think is usefull to have as default.
-	[detection] : peak positive. It is the case for me, for Louis, and before the confinment when we tried with the Valerio’s data it was also the case.
-	[fitting] : collect_all = true. It is usefull in Phy to have a garbage template so you see in the raw data if spikes where detected but not fitted.
-	Converting : removing ‘prompt’ for exporting pcs because creates error when launched on the cluster. Export all = true, to see garbage templates. Prelabelling=true, so Phy suggests if some unit are sua, mua or noise.

Cheers
Paul

### CODE REVIEW

**Comment by stephenwhitmarsh** [comment]
Hi Paul,

Don't change defaults because it works better for you or louis. That is not
a reason - anyone can then just change defaults to fit their preference!

Instead, two sustainable and 'social' options:
1) add settings in the config which will overwrite existing defaults;
2) create a setting in config with a path to a user-defined 'default'
params file.

cheers,
s



Op ma 22 jun. 2020 om 12:31 schreef Paul-Baudin <notifications@github.com>:

**Comment by Paul-Baudin** [comment]
This is not only for Louis or me. This is also for Valerio, and, so, probably, for all the 'Epimicro' data as the acquisition is done with the same amplifier and the same parameters. I though it was a sufficient reason, but sure, maybe better to have it in the cfg.

I updated this field so it is set as negative in this PR, as it was before

**Comment by stephenwhitmarsh** [comment]
sure, it's a matter of degree - what I mean is that it's not a question of
choosing one default versus another but to make those settings that can
change between users/labs explicit, i.e. user-defined, and thereby
improving transparency - which was lacking in this one, and thereby
improving the code.

cheers and thanks,
s

Op ma 22 jun. 2020 om 12:51 schreef Paul-Baudin <notifications@github.com>:

**Comment by stephenwhitmarsh** [comment]
think of it in this way: 'default' settings should only occur where it
doesn't matter much. So by identifying those defaults that do matter, and
making them obligatory for the user to decide on, makes the code better.

Op ma 22 jun. 2020 om 12:59 schreef Stephen Whitmarsh <
stephen.whitmarsh@gmail.com>:

**Comment by Paul-Baudin** [comment]
Yes I think it is a very good idea, it would be easier to modify the spyking circus parameters that matter in the config 'setparams' instead of searching the template file.

I suggest this list of parameters : 
data.spike_thresh
data.peaks
filtering.cut_off
clustering.nb_elts
clustering.nb_repeats
clustering.merging_method
clustering.merging_param
clustering.sensitivity
clustering.cc_merge

And what I modified in this PR, for getting garbage templates, and converting options, I would think it can be left as default and do not need to be modified.

**Comment by stephenwhitmarsh** [comment]
okay!
last thing though - all those setttings should be in the .circus field, to
keep overview and prevent namespace
<https://en.wikipedia.org/wiki/Namespace>conflicts (i.e. i am working on a
cluster function that uses cfg.cluster.xxx :-))

I.e.:

cfg.circus data.spike_thresh
cfg.circus.filtering.cut_off
etc.

thanks,
s

Op ma 22 jun. 2020 om 13:23 schreef Paul-Baudin <notifications@github.com>:

**Comment by Paul-Baudin** [comment]
OK ! I will answer to this PR with those modifs later

**Comment by Paul-Baudin** [comment]
I just pushed another modif.  I removed the modif of the template params in EpiCode/templates. Instead, I put an optional config field in writeSpykingCircusParameters to have my own default template file. If this config field is absent the script still uses the template in EpiCode/template

**Comment by stephenwhitmarsh** [comment]
Hi Paul, is this still your latest version, or do you want me to close it and start fresh?

**Comment by Paul-Baudin** [comment]
The changes of writeSpykingCircusParameters.m (add optional .params file) were added with the wod project #27 
But now with my better use of Git this situation will not happen anymore, it will be much easier to track modifications, with different branches as we just discussed. 

My solution for now is to update my own .param file with my default parameters (which change for each project/kind of data), and to call it with cfg.circus.paramfile
This PR can be closed but maybe you would have better ideas of how to deal with those spyking-circus parameters.

**Comment by stephenwhitmarsh** [comment]
I like the use of project-specific parameter files! Sound like the best solution to me.

**Pull request closed without merging**
