### PR TITLE
Use nev

### PR DESCRIPTION
**Pull request by Paul-Baudin**
Hi Stephen,

I need to work with TTL events recorded by my Neuralynx amplifier. They are stored in one .nev file, in each Neuralynx data directory.

1/ While reading the nev file with read_neuralynx_nev, the output event structure contains not only a code for each event, but also a string with the name I put in my acquisition config for this event. When I use ft_read_event, I loose this string. I think it is easier to work with the string name as it is more explicit. To have the string name associated with the event, do you think it is better to use directly read_neuralynx_nev.m (which I have to move because it is in a 'private' folder), or to use ft_read_event with the little modification I put in this PR ? (see /development/modified_fieldtrip_functions, 2 lines commented with '%Paul').

2/ To vizualize the event location in Muse, and to use it the same way as I use manually-set markers, I suggest this function (projects/dtx/to_share/read_nev_Muse) to write the nev events into the muse structure. Do you think it is a good way of doing it ?

3/ You still see the commits from the last PR because I did'nt create a specific branch for it. But I cancelled it by deleting the function edit_Markerfiles.m in the dtx folder, so there is now only the funtion editMuseMakers in the shared folder. 

Thanks a lot for your help

Paul

### CODE REVIEW

**Comment by Paul-Baudin** [comment]
This PR is about the function DTX/to_share/read_nev_Muse.
You do not see this in the 'Files changed' because it was added to the master with the synchronization of #33

**Comment by stephenwhitmarsh** [comment]
1/ I would do it differently and keep the altered fieldtrip function in your _fieldtrip_ repository. Why not do the following:
a) If you haven't done so yet, fork www.github.com/fieldtrip/fieldtrip. Then clone it on the server/ your computer. Set up remote upstream and origin. Use that local repository in your MATLAB path and remove any old ones to prevent mistakes.
b) Make the change to read_neuralynx that you need, then push it to your own remote repository (origin)
c) Do a PR to /fieldtrip/fieldtrip with a short and clear description why. With a bit of luck your PR gets merged.
d) Regularly do a "pull upstream master" then "push origin master" to keep your local and remote repo updated to any changes done to the fieldtrip repo.

2/ Sounds good. You can put it in /shared if you want.

3/ ok

**Comment by Paul-Baudin** [comment]
Thanks for the answer. I think finally that it is not a good idea to change the output of ft_read_event as it seems to be a very commonly used function, with an output which likely needs to stay standardized.
I copied read_neuralynx_nev into the external/fieldtrip folder, because it was in a private folder so I could'nt call it directly. I had also to move 3 other functions which were in the private folder and which are needed. 
I moved read_nev_Muse into /shared and add a header. 
Let me know if there is anything :)

**Comment by Paul-Baudin** [comment]
Note that doing that, I do not need to modify read_neuralynx_nev

**Pull request merged**
